spring:
  application:
    name: resilience

resilience4j.circuitbreaker:
    instances:
      test:
        sliding-window-type: count_based
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        record-exceptions:
          - java.lang.RuntimeException